### ISSUE TITLE
cant auth in web panel

### ISSUE THREAD

**Issue by Genry777Morgan** [bhopkins0/OpenVPN-WebAdmin#1]
![image](https://user-images.githubusercontent.com/55747868/158082066-e2139c62-b205-4c8e-bc87-a2e5b8983578.png)

**Comment by Genry777Morgan** [comment]
I solved the problem by installing more modules and re-permissioning the folder

**Comment by Genry777Morgan** [comment]
When will there be an update that will have more functionality? (the ability to enable obfuscation, additional user settings, control via telegram bot)

**Comment by bhopkins0** [comment]
I intend to provide an update within a few weeks to add more functionality. I'll probably add the following features:

* API for creating, deleting, and listing clients
* Ability to change the admin password
* Ability to change the DNS servers used by the VPN
* Ability to change the port the VPN runs on

Regarding control via telegram bot and adding obfuscation, I do not plan on adding those features since I am not familiar with obsf4 or telegram bots.
